# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scdl-qt.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(706, 374)
        MainWindow.setStatusTip("")
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tokenText = QtWidgets.QLineEdit(self.centralwidget)
        self.tokenText.setGeometry(QtCore.QRect(10, 330, 201, 20))
        self.tokenText.setText("")
        self.tokenText.setObjectName("tokenText")
        self.streamRadio = QtWidgets.QRadioButton(self.centralwidget)
        self.streamRadio.setGeometry(QtCore.QRect(40, 30, 82, 17))
        self.streamRadio.setChecked(True)
        self.streamRadio.setObjectName("streamRadio")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(130, 30, 71, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 310, 111, 16))
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(220, 330, 471, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.logTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.logTextEdit.setGeometry(QtCore.QRect(10, 120, 501, 191))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.logTextEdit.setPalette(palette)
        self.logTextEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.logTextEdit.setReadOnly(False)
        self.logTextEdit.setObjectName("logTextEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 111, 16))
        self.label_2.setObjectName("label_2")
        self.go = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.go.setGeometry(QtCore.QRect(580, 280, 111, 41))
        self.go.setObjectName("go")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 60, 81, 16))
        self.label_3.setObjectName("label_3")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(521, 111, 165, 16))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(521, 129, 165, 16))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(521, 147, 165, 16))
        self.checkBox_3.setObjectName("checkBox_3")
        self.output = QtWidgets.QListWidget(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(130, 110, 256, 192))
        self.output.setObjectName("output")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(170, 20, 521, 71))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.urlText = QtWidgets.QLineEdit(self.widget)
        self.urlText.setObjectName("urlText")
        self.gridLayout.addWidget(self.urlText, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 1, 1, 1)
        self.pathText = QtWidgets.QLineEdit(self.widget)
        self.pathText.setObjectName("pathText")
        self.gridLayout.addWidget(self.pathText, 1, 0, 1, 1)
        self.btnBrowse = QtWidgets.QPushButton(self.widget)
        self.btnBrowse.setObjectName("btnBrowse")
        self.gridLayout.addWidget(self.btnBrowse, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "scdl-qt :)"))
        self.streamRadio.setText(_translate("MainWindow", "My Stream"))
        self.radioButton_2.setText(_translate("MainWindow", "URL"))
        self.label.setText(_translate("MainWindow", "sc token for stream dl"))
        self.logTextEdit.setPlainText(_translate("MainWindow", "coucou\n"
""))
        self.label_2.setText(_translate("MainWindow", "debug"))
        self.go.setText(_translate("MainWindow", "Download"))
        self.label_3.setText(_translate("MainWindow", "download folder"))
        self.checkBox.setText(_translate("MainWindow", "Continue if file already exists"))
        self.checkBox_2.setText(_translate("MainWindow", "Add artist to file name"))
        self.checkBox_3.setText(_translate("MainWindow", "Download mp3 only (128kbits)"))
        self.urlText.setText(_translate("MainWindow", "https://soundcloud.com/iamdjday/four-hills"))
        self.pushButton.setText(_translate("MainWindow", "Paste"))
        self.btnBrowse.setText(_translate("MainWindow", "Browse"))

