# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scdl-qt.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(704, 373)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        MainWindow.setStatusTip("")
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("#MainWindow {\n"
"background: gray;\n"
"}\n"
"QLineEdit {\n"
"padding: 0.5px;\n"
"border-style: solid;\n"
"\n"
"\n"
"background: lightgray;\n"
"}\n"
"\n"
"\n"
"QProgressBar {\n"
"\n"
"\n"
"\n"
"background: gray;\n"
"border-size=0px;\n"
"\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"background: black;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.streamRadio = QtWidgets.QRadioButton(self.centralwidget)
        self.streamRadio.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.streamRadio.setChecked(True)
        self.streamRadio.setObjectName("streamRadio")
        self.alltracksRadio = QtWidgets.QRadioButton(self.centralwidget)
        self.alltracksRadio.setGeometry(QtCore.QRect(91, 21, 115, 16))
        self.alltracksRadio.setObjectName("alltracksRadio")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 310, 111, 16))
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(320, 330, 371, 23))
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.logTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.logTextEdit.setGeometry(QtCore.QRect(10, 120, 501, 191))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.logTextEdit.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.logTextEdit.setFont(font)
        self.logTextEdit.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.logTextEdit.setReadOnly(False)
        self.logTextEdit.setObjectName("logTextEdit")
        self.urlText = QtWidgets.QLineEdit(self.centralwidget)
        self.urlText.setGeometry(QtCore.QRect(90, 40, 431, 20))
        self.urlText.setObjectName("urlText")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 111, 16))
        self.label_2.setObjectName("label_2")
        self.go = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.go.setEnabled(True)
        self.go.setGeometry(QtCore.QRect(550, 260, 101, 41))
        palette = QtGui.QPalette()
        self.go.setPalette(palette)
        self.go.setObjectName("go")
        self.btnBrowse = QtWidgets.QPushButton(self.centralwidget)
        self.btnBrowse.setGeometry(QtCore.QRect(450, 90, 62, 21))
        self.btnBrowse.setFlat(False)
        self.btnBrowse.setObjectName("btnBrowse")
        self.pathText = QtWidgets.QLineEdit(self.centralwidget)
        self.pathText.setGeometry(QtCore.QRect(90, 90, 351, 20))
        self.pathText.setObjectName("pathText")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 70, 81, 16))
        self.label_3.setObjectName("label_3")
        self.cBox = QtWidgets.QCheckBox(self.centralwidget)
        self.cBox.setEnabled(True)
        self.cBox.setGeometry(QtCore.QRect(521, 161, 162, 17))
        self.cBox.setChecked(False)
        self.cBox.setObjectName("cBox")
        self.mp3Box = QtWidgets.QCheckBox(self.centralwidget)
        self.mp3Box.setEnabled(True)
        self.mp3Box.setGeometry(QtCore.QRect(520, 190, 167, 17))
        self.mp3Box.setObjectName("mp3Box")
        self.allfavsRadio = QtWidgets.QRadioButton(self.centralwidget)
        self.allfavsRadio.setEnabled(True)
        self.allfavsRadio.setGeometry(QtCore.QRect(210, 20, 101, 16))
        self.allfavsRadio.setObjectName("allfavsRadio")
        self.playlistRadio = QtWidgets.QRadioButton(self.centralwidget)
        self.playlistRadio.setEnabled(True)
        self.playlistRadio.setGeometry(QtCore.QRect(370, 20, 115, 16))
        self.playlistRadio.setObjectName("playlistRadio")
        self.rBox = QtWidgets.QCheckBox(self.centralwidget)
        self.rBox.setEnabled(True)
        self.rBox.setGeometry(QtCore.QRect(521, 220, 94, 17))
        self.rBox.setObjectName("rBox")
        self.gettokenButton = QtWidgets.QPushButton(self.centralwidget)
        self.gettokenButton.setGeometry(QtCore.QRect(10, 40, 71, 21))
        self.gettokenButton.setObjectName("gettokenButton")
        self.trackRadio = QtWidgets.QRadioButton(self.centralwidget)
        self.trackRadio.setEnabled(True)
        self.trackRadio.setGeometry(QtCore.QRect(320, 20, 51, 16))
        self.trackRadio.setObjectName("trackRadio")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(530, 140, 151, 16))
        self.label_4.setObjectName("label_4")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(220, 330, 81, 21))
        self.saveButton.setObjectName("saveButton")
        self.tokenText = QtWidgets.QLineEdit(self.centralwidget)
        self.tokenText.setGeometry(QtCore.QRect(10, 330, 201, 20))
        self.tokenText.setText("")
        self.tokenText.setObjectName("tokenText")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "scdl-qt :)"))
        self.streamRadio.setText(_translate("MainWindow", "My Stream"))
        self.alltracksRadio.setText(_translate("MainWindow", "All Tracks from URL"))
        self.label.setText(_translate("MainWindow", "sc token for stream dl"))
        self.logTextEdit.setPlainText(_translate("MainWindow", "coucou\n"
""))
        self.urlText.setText(_translate("MainWindow", "https://soundcloud.com/iamdjday/four-hills"))
        self.label_2.setText(_translate("MainWindow", "debug"))
        self.go.setText(_translate("MainWindow", "Download"))
        self.btnBrowse.setText(_translate("MainWindow", "Browse"))
        self.label_3.setText(_translate("MainWindow", "download folder"))
        self.cBox.setText(_translate("MainWindow", "Overwrite files"))
        self.mp3Box.setText(_translate("MainWindow", "Download mp3 only (128kbits)"))
        self.allfavsRadio.setText(_translate("MainWindow", "All Favs from URL"))
        self.playlistRadio.setText(_translate("MainWindow", "Playlist"))
        self.rBox.setText(_translate("MainWindow", "Ignore reposts"))
        self.gettokenButton.setText(_translate("MainWindow", "get sc token"))
        self.trackRadio.setText(_translate("MainWindow", "Track"))
        self.label_4.setText(_translate("MainWindow", "options not implemented yet"))
        self.saveButton.setText(_translate("MainWindow", "save to config"))

